#!/bin/sh

## Description: Print the port name as was the port 'origin' for each
## package specified in $@, using local package repository information

## FIXME - Note that the pkg-query utility, as called below, exits
## with a zero exit status, even if there is no package name for the
## specified query. Ideally, it should exit with a non-zero exit code,
## in such situation.
##
## Similar for pkg-rquery

## See also:
##  * pkg-query(8)
##  * utility script 'pkg-port-pkg' and notes

exec pkg query "%o" "$@"
