#!/bin/sh

## Description: Print the package name for the package that would be
## built from each port specified in $@, using local package
## repository information

## see also: 
## * pkg-update(8)
## * pkg-query(8)
## * utility script 'pkg-port' and notes


## FIXME - Note that the pkg-query utility, as called below, exits
## with a zero exit status, even if there is no package name for the
## specified query. Ideally, it should exit with a non-zero exit code,
## in such situation.
##
## Similar for pkg-rquery

## FIXME: this script now uses 'pkg query' instead of 'pkg rquery'
## Thus, this script's applicability may be limited to the set of
## installed packages.
##
## Note: Synchronization of local, remote databases for port, package metadata

exec pkg query "%n" "$@:

